# Generated by Django 5.2.7 on 2026-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description given'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(),
        ),
    ]
