# Generated by Django 6.0.6 on 2026-06-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='pet')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('happiness', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('equipped_clothes', models.IntegerField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
