# Generated by Django 6.0.6 on 2026-07-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_task_description_alter_task_name'),
        ('quickstart', '0002_pet'),
    ]

    operations = [
    ]
