# Generated by Django 6.0.6 on 2026-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_merge_20260728_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyuser',
            name='canvas_ics_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='canvas_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('canvas_uid__isnull', False)), fields=('user', 'canvas_uid'), name='unique_canvas_task_per_user'),
        ),
    ]
